inserção da função delete e do README
rayellyv/ApiCompras pull request #2
Opened 2022-02-15 15:28 UTC by rayellyv

- Inserção da função delete
- Construção do README do projeto

Board:

[#37270](https://dev.azure.com/vortxrepositories/CEO%20Generation%20-%20IA%20Freshdesk%20e%20URA/_sprints/taskboard/CEO%20Generation%20-%20IA%20Freshdesk%20e%20URA%20Team/CEO%20Generation%20-%20IA%20Freshdesk%20e%20URA/Sprint%201?workitem=36571)

2022-02-15 15:47 UTC, maikvortx requested changes

2022-02-15 15:47 UTC, maikvortx commented on README.md
> +Essas instruções permitirão que você obtenha uma cópia do projeto em operação na sua máquina local para fins de desenvolvimento e teste.
Ray, você acha que aqui podemos colocar o comando para rodar o projeto?

2022-02-15 20:22 UTC, rayellyv commented on README.md
> +Essas instruções permitirão que você obtenha uma cópia do projeto em operação na sua máquina local para fins de desenvolvimento e teste.
Maik, achas que assim ficaria bom:

## 🚀 Começando

Ao acessar o projeto no seu PC, deve dar o comando npm install, aguardar a instalção e posteriormente
o comando npm run start.

2022-02-15 20:23 UTC, rayellyv commented on README.md
> +Essas instruções permitirão que você obtenha uma cópia do projeto em operação na sua máquina local para fins de desenvolvimento e teste.
Maik, achas que assim ficaria bom?

🚀 Começando
Ao acessar o projeto no seu PC, deve dar o comando npm install, aguardar a instalção e posteriormente
o comando npm run start

2022-02-16 15:02 UTC, maikvortx commented on README.md
> +Essas instruções permitirão que você obtenha uma cópia do projeto em operação na sua máquina local para fins de desenvolvimento e teste.
Acho que fica legal sim! Podemos atualizar a doc.

2022-02-16 15:04 UTC, rayellyv commented on README.md
> +Essas instruções permitirão que você obtenha uma cópia do projeto em operação na sua máquina local para fins de desenvolvimento e teste.
Massa Maik, vou fazer um novo pull request

2022-02-16 15:22 UTC, maikvortx commented on README.md
> +Essas instruções permitirão que você obtenha uma cópia do projeto em operação na sua máquina local para fins de desenvolvimento e teste.
Não precisa outro Pull Request! Basta você fazer um PUSH das alterações na branch da Task e ele já atualiza este PR.

2022-02-17 02:25 UTC, merged